/*
 * error.h
 *
 *  Created on: Apr 28, 2015
 *      Author: johnnyc
 */

#ifndef _SYNOISCSIEP_ERROR_H_
#define _SYNOISCSIEP_ERROR_H_

#include <errno.h>
#include <synocore/synoglobal.h>

__BEGIN_DECLS

#define ISCSI_BASE_ERROR_CODE_BASIC       18990000
#define ISCSI_BASE_ERROR_CODE_WEBAPI      18990200
#define ISCSI_BASE_ERROR_CODE_DSM         18990300
#define ISCSI_BASE_ERROR_CODE_ISCSI       18990400
#define ISCSI_BASE_ERROR_CODE_LUN         18990500
#define ISCSI_BASE_ERROR_CODE_TARGET      18990700
#define ISCSI_BASE_ERROR_CODE_REPLICATION 18990800
#define ISCSI_BASE_ERROR_CODE_VLUN        18991000
#define ISCSI_BASE_ERROR_CODE_NODE        18991100
#define ISCSI_BASE_ERROR_CODE_LUNBKP      18991200

/***********************************************************************************************/
/*  MUST READ: If add a new error code here, please add a corresponding error string as well.  */
/***********************************************************************************************/
typedef enum _tag_iscsi_error_code {
	ERR_ISCSI_SUCCESS                            = 0,  // ERR_ISCSI_SUCCESS MUST always be zero.

	/*** Basic ***/
	ERR_ISCSI_DEFAULT_ERROR_CODE                 = ISCSI_BASE_ERROR_CODE_BASIC,
	ERR_ISCSI_OUT_OF_MEMORY,
	ERR_ISCSI_OUT_OF_FREE_SPACE,
	ERR_ISCSI_NULL_POINTER,
	ERR_ISCSI_BAD_PARAMETER,
	ERR_ISCSI_BAD_FILE_SYSTEM_TYPE,
	ERR_ISCSI_BAD_FILE_TYPE,
	ERR_ISCSI_BAD_FILE_SIZE,
	ERR_ISCSI_BAD_STRING_LENGTH,
	ERR_ISCSI_NO_PERMISSION,
	ERR_ISCSI_TIMEOUT,
	ERR_ISCSI_FILE_NOT_FOUND,
	ERR_ISCSI_FILE_EXISTS,
	ERR_ISCSI_TRY_AGAIN,
	ERR_ISCSI_FAILED_TO_FORK,
	ERR_ISCSI_FAILED_TO_LOCK_FILE,
	ERR_ISCSI_FAILED_TO_UNLOCK_FILE,
	ERR_ISCSI_FAILED_TO_GET_FILE_SESSION,
	ERR_ISCSI_FAILED_TO_SET_FILE_SESSION,
	ERR_ISCSI_FAILED_TO_ADD_FILE_SESSION,
	ERR_ISCSI_FAILED_TO_REMOVE_FILE_SESSION,
	ERR_ISCSI_FAILED_TO_STAT_PATH,
	ERR_ISCSI_FAILED_TO_ACCESS_PATH,
	ERR_ISCSI_FAILED_TO_TOUCH_FILE,
	ERR_ISCSI_FAILED_TO_CLOSE_FILE,
	ERR_ISCSI_FAILED_TO_COPY_STRING,
	ERR_ISCSI_FAILED_TO_OPEN_DIRECTORY,
	ERR_ISCSI_FAILED_TO_CLOSE_DIRECTORY,
	ERR_ISCSI_FAILED_TO_CREATE_DIRECTORY,
	ERR_ISCSI_FAILED_TO_REMOVE_DIRECTORY,
	ERR_ISCSI_FAILED_TO_INSMOD,
	ERR_ISCSI_FAILED_TO_RMMOD,
	ERR_ISCSI_FAILED_TO_SET_HASH_VALUE,
	ERR_ISCSI_FAILED_TO_GET_HASH_VALUE,
	ERR_ISCSI_FAILED_TO_SET_PAIRS,
	ERR_ISCSI_FAILED_TO_GET_PAIRS,
	ERR_ISCSI_FAILED_TO_LINK_FILE,
	ERR_ISCSI_FAILED_TO_UNLINK_FILE,
	ERR_ISCSI_FAILED_TO_OPEN_FILE,
	ERR_ISCSI_FAILED_TO_READ_FILE,
	ERR_ISCSI_FAILED_TO_WRITE_FILE,
	ERR_ISCSI_FAILED_TO_SEEK_FILE,
	ERR_ISCSI_FAILED_TO_RENAME_FILE,
	ERR_ISCSI_FAILED_TO_COPY_FILE,
	ERR_ISCSI_FAILED_TO_GLOB,
	ERR_ISCSI_FAILED_TO_START_SERVICE,
	ERR_ISCSI_FAILED_TO_STOP_SERVICE,
	ERR_ISCSI_FAILED_TO_GET_FILE_PATH,
	ERR_ISCSI_FAILED_TO_ALLOCATE_FILE,
	ERR_ISCSI_FAILED_TO_GET_TIME,
	ERR_ISCSI_FAILED_TO_PARSE_STRING,
	ERR_ISCSI_FAILED_TO_GET_HOSTENT,
	ERR_ISCSI_FAILED_TO_GET_FILE_SYSTEM_INFO,
	ERR_ISCSI_FAILED_TO_PIN_VOLUME,
	ERR_ISCSI_FAILED_TO_MOUNT,
	ERR_ISCSI_FAILED_TO_GET_HOSTNAME,
	ERR_ISCSI_FAILED_TO_GET_TRUNCATE_MODE,
	ERR_ISCSI_FAILED_TO_TRUNCATE_FILE,
	ERR_ISCSI_DIRECTORY_EXISTS,
	ERR_ISCSI_FAILED_TO_ENUMERATE_DIRECTORY,
	ERR_ISCSI_FAILED_TO_RENAME_DIRECTORY,
	ERR_ISCSI_FAILED_TO_KILL,
	// End of Basic error code
	ERR_ISCSI_MAX_ERROR_CODE_BASIC,

	/*** WebAPI ***/
	ERR_ISCSI_NO_SUCH_API                        = ISCSI_BASE_ERROR_CODE_WEBAPI,
	ERR_ISCSI_INVAILD_INPUT,
	ERR_ISCSI_BAD_CLIENT_INPUT,
	ERR_ISCSI_BAD_IP,
	ERR_ISCSI_BAD_RESPONSE,
	ERR_ISCSI_FAILED_TO_LOGIN,
	ERR_ISCSI_FAILED_TO_LOGOUT,
	ERR_ISCSI_FAILED_TO_CREATE_REQUEST,
	ERR_ISCSI_FAILED_TO_CONVERT_TO_JSON,
	ERR_ISCSI_FAILED_TO_GET_UUID,
	ERR_ISCSI_FAILED_TO_GET_SESSION_ID,
	ERR_ISCSI_FAILED_TO_SEND_THE_REQUEST,
	ERR_ISCSI_FAILED_TO_GET_ERROR_CODE,
	ERR_ISCSI_NOT_IMPLEMENTED_YET,
	// End of WebAPI error code
	ERR_ISCSI_MAX_ERROR_CODE_WEBAPI,

	/*** DSM ***/
	ERR_ISCSI_FAILED_TO_GET_VOLUME_INFO          = ISCSI_BASE_ERROR_CODE_DSM,
	ERR_ISCSI_FAILED_TO_ENUMERATE_SECTION,
	ERR_ISCSI_FAILED_TO_ENUMERATE_CONF_SECTION,
	ERR_ISCSI_FAILED_TO_GET_SECTION,
	ERR_ISCSI_FAILED_TO_ADD_SECTION,
	ERR_ISCSI_FAILED_TO_SET_SECTION,
	ERR_ISCSI_FAILED_TO_REMOVE_SECTION,
	ERR_ISCSI_FAILED_TO_MODIFY_SECTION,
	ERR_ISCSI_FAILED_TO_PUSH_TO_LIST,
	ERR_ISCSI_FAILED_TO_GET_FROM_LIST,
	ERR_ISCSI_FAILED_TO_PARSE_HEADER,
	ERR_ISCSI_FAILED_TO_PARSE_VOLUME_ID,
	ERR_ISCSI_FAILED_TO_INIT_PLUGIN_HOOK,
	ERR_ISCSI_FAILED_TO_RUN_PLUGIN_ACTION,
	ERR_ISCSI_FAILED_TO_GET_SERIAL_NUMBER,
	ERR_ISCSI_FAILED_TO_SEND_NOTIFICATION,
	ERR_ISCSI_FAILED_TO_GET_SPACE_DEVICE_SIZE,
	ERR_ISCSI_FAILED_TO_CREATE_BTRFS_SUBVOLUME,
	ERR_ISCSI_FAILED_TO_DELETE_BTRFS_SUBVOLUME,
	ERR_ISCSI_FAILED_TO_GET_NET_INTERFACE,
	ERR_ISCSI_FAILED_TO_GET_NIC_PCI_NAME,
	ERR_ISCSI_FAILED_TO_GET_HW_VENDOR,
	// End of DSM error code
	ERR_ISCSI_MAX_ERROR_CODE_DSM,

	/*** iSCSI ***/
	ERR_ISCSI_BAD_EP_FILE_TYPE                   = ISCSI_BASE_ERROR_CODE_ISCSI,
	ERR_ISCSI_BAD_EP_FILE_PATH,
	ERR_ISCSI_BAD_PORTALS,
	ERR_ISCSI_BAD_DESCRIPTION,
	ERR_ISCSI_BAD_DELETED_BY,
	ERR_ISCSI_NEED_LIO_SUPPORT,
	ERR_ISCSI_NO_PORTALS,
	ERR_ISCSI_NO_PLUGIN_NOTIFIED,
	ERR_ISCSI_FAILED_TO_PLUGIN_NOTIFY,
	ERR_ISCSI_FAILED_TO_PLUGIN_START,
	ERR_ISCSI_FAILED_TO_PLUGIN_END,
	ERR_ISCSI_FAILED_TO_CREATE_OBJECT_FILE,
	ERR_ISCSI_FAILED_TO_CREATE_COMMUNICATION,
	ERR_ISCSI_FAILED_TO_FILL_EP_FILE,
	ERR_ISCSI_FAILED_TO_GET_MAPPED_SIZE,
	ERR_ISCSI_FAILED_TO_ADD_EXTENT_POOL,
	ERR_ISCSI_FAILED_TO_CREATE_EPIO_JOURNAL,
	ERR_ISCSI_INCONSISTENT_EPIO_JOURNAL,
	ERR_ISCSI_FAILED_TO_ENABLE_EXTENT_POOL,
	ERR_ISCSI_FAILED_TO_DISABLE_EXTENT_POOL,
	ERR_ISCSI_FAILED_TO_SET_VOLUME_ID,
	ERR_ISCSI_FAILED_TO_SET_MAP_FILE_PATH,
	ERR_ISCSI_FAILED_TO_CREATE_PROGRESS_FILE,
	ERR_ISCSI_FAILED_TO_DELETE_PROGRESS_FILE,
	ERR_ISCSI_FAILED_TO_SET_PROGRESS_FILE,
	ERR_ISCSI_FAILED_TO_GET_ISCSICONFIG,
	ERR_ISCSI_FAILED_TO_GENERATE_UUID,
	ERR_ISCSI_ISCSI_DIR_NOT_FOUND,
	ERR_ISCSI_ISCSI_BAD_PORT,
	ERR_ISCSI_FAILED_TO_GET_SPACE_PATH_OF_VSPACE,
	ERR_ISCSI_NOT_ACCEPTED_BY_FILTER,
	ERR_ISCSI_PLUGIN_ABORT_DEPART_TASK,
	// End of iSCSI error code
	ERR_ISCSI_MAX_ERROR_CODE_ISCSI,

	/*** LUN ***/
	ERR_ISCSI_BAD_LUN_TYPE                       = ISCSI_BASE_ERROR_CODE_LUN,
	ERR_ISCSI_BAD_LUN_LOCATION,
	ERR_ISCSI_BAD_LUN_SIZE,
	ERR_ISCSI_BAD_LUN_NAME,
	ERR_ISCSI_BAD_LUN_ID,
	ERR_ISCSI_BAD_LUN_UUID,
	ERR_ISCSI_BAD_LUN_IS_SAME_POOL,
	ERR_ISCSI_BAD_LUN_EXTENT_SIZE,
	ERR_ISCSI_BAD_SRC_LUN_UUID,
	ERR_ISCSI_BAD_DST_LUN_UUID,
	ERR_ISCSI_BAD_EXPORTING_LOCATION,
	ERR_ISCSI_BAD_EXPORTING_LUN_NAME,
	ERR_ISCSI_BAD_EXPORTED_LUN_UUID,
	ERR_ISCSI_BAD_SNAPSHOT_NAME,
	ERR_ISCSI_BAD_IS_LOCKED,
	ERR_ISCSI_BAD_IS_APP_CONSISTENT,
	ERR_ISCSI_BAD_IS_COUNT_ONLY,
	ERR_ISCSI_BAD_ADDITIONAL,
	ERR_ISCSI_BAD_SNAPSHOT_NOTE,
	ERR_ISCSI_BAD_SNAPSHOT_ID,
	ERR_ISCSI_BAD_SNAPSHOT_UUID,
	ERR_ISCSI_BAD_SNAPSHOT_TIME,
	ERR_ISCSI_BAD_NEW_NAME,
	ERR_ISCSI_BAD_NEW_SIZE,
	ERR_ISCSI_BAD_APP_KEY,
	ERR_ISCSI_BAD_EXPORT_STATUS,
	ERR_ISCSI_BAD_IMPORT_STATUS,
	ERR_ISCSI_BAD_IS_SCHEDULED,
	ERR_ISCSI_BAD_IS_FOR_TRASH,
	ERR_ISCSI_BAD_IS_FOR_UNSYNC_SIZE,
	ERR_ISCSI_NO_LUN_UUID,
	ERR_ISCSI_NO_SUCH_LUN,
	ERR_ISCSI_NO_SUCH_SNAPSHOT,
	ERR_ISCSI_NO_SUCH_FAMILY,
	ERR_ISCSI_LUN_IS_MAPPED,
	ERR_ISCSI_LUN_IS_LOCKED,
	ERR_ISCSI_LUN_NOT_LOADED,
	ERR_ISCSI_LUN_CONFIG_REPAIRED,
	ERR_ISCSI_DUPLICATED_LUN_NAME,
	ERR_ISCSI_CONNOT_CLONE_BLOCK_LUN,
	ERR_ISCSI_CONNOT_DELETE_LOCKED_SNAPSHOT,
	ERR_ISCSI_REACH_MAX_LUN_COUNT,
	ERR_ISCSI_REACH_MAX_TARGET_COUNT,
	ERR_ISCSI_REACH_MAX_SNAPSHOT_COUNT,
	ERR_ISCSI_FAMILY_CONFIG_REPAIRED,
	ERR_ISCSI_SNAPSHOT_CONFIG_REPAIRED,
	ERR_ISCSI_SNAPSHOT_NOT_LOADED,
	ERR_ISCSI_SNAPSHOT_IS_LOCKED,
	ERR_ISCSI_FAILED_TO_CREATE_LUN,
	ERR_ISCSI_FAILED_TO_CONVERT_TO_SINK,
	ERR_ISCSI_FAILED_TO_LOAD_LUN_CONFIG,
	ERR_ISCSI_FAILED_TO_DELETE_LUN,
	ERR_ISCSI_FAILED_TO_CLONE_LUN,
	ERR_ISCSI_FAILED_TO_MIRROR_LUN,
	ERR_ISCSI_FAILED_TO_PROMOTE_LUN,
	ERR_ISCSI_FAILED_TO_GET_LUN_ID,
	ERR_ISCSI_FAILED_TO_ADD_LUN_CONFIG,
	ERR_ISCSI_FAILED_TO_LIST_LUN,
	ERR_ISCSI_FAILED_TO_LOAD_FAMILY_CONFIG,
	ERR_ISCSI_FAILED_TO_ADD_FAMILY_CONFIG,
	ERR_ISCSI_FAILED_TO_REMOVE_FAMILY_CONFIG,
	ERR_ISCSI_FAILED_TO_REMOVE_SNAPSHOT,
	ERR_ISCSI_FAILED_TO_REMOVE_RETENTION_POLICY,
	ERR_ISCSI_FAILED_TO_RUN_RETENTION_POLICY,
	ERR_ISCSI_FAILED_TO_REMOVE_LUN_BACKUP_TASK,
	ERR_ISCSI_FAILED_TO_REMOVE_SCHEDULE_SNAPSHOT_TASK,
	ERR_ISCSI_FAILED_TO_GET_EXTENT_SIZE,
	ERR_ISCSI_FAILED_TO_GET_SNAPSHOT_COUNT,
	ERR_ISCSI_FAILED_TO_ACCESS_FAMILY_CONFIG,
	ERR_ISCSI_FAILED_TO_TAKE_A_SNAPSHOT,
	ERR_ISCSI_FAILED_TO_MAP_TARGET,
	ERR_ISCSI_FAILED_TO_GET_SNAPSHOT_INFO,
	ERR_ISCSI_FAILED_TO_GET_NEW_SNAPSHOT_NAME,
	ERR_ISCSI_FAILED_TO_LOAD_SNAPSHOT_CONFIG,
	ERR_ISCSI_FAILED_TO_CLONE_SNAPSHOT,
	ERR_ISCSI_FAILED_TO_LOAD_SNAPSHOT,
	ERR_ISCSI_FAILED_TO_UNLOAD_SNAPSHOT,
	ERR_ISCSI_FAILED_TO_ENABLE_SNAPSHOT,
	ERR_ISCSI_FAILED_TO_LOAD_LUN,
	ERR_ISCSI_FAILED_TO_UNLOAD_LUN,
	ERR_ISCSI_FAILED_TO_GET_UNUSED_LID,
	ERR_ISCSI_FAILED_TO_GET_UNUSED_SID,
	ERR_ISCSI_FAILED_TO_UPDATE_LUN,
	ERR_ISCSI_FAILED_TO_UPDATE_LUN_BACKUP_TASK,
	ERR_ISCSI_FAILED_TO_PASS_SPACE_CHECK,
	ERR_ISCSI_FAILED_TO_FINISH_EXPORT,
	ERR_ISCSI_FAILED_TO_FINISH_IMPORT,
	ERR_ISCSI_FAILED_TO_GET_LUN_STATUS,
	ERR_ISCSI_EXPORT_INTERRUPT,
	ERR_ISCSI_IMPORT_INTERRUPT,
	ERR_ISCSI_NOW_IS_EXPORTING,
	ERR_ISCSI_NOW_IS_IMPORTING,
	ERR_ISCSI_NOW_IS_NOT_EXPORTING,
	ERR_ISCSI_NOW_IS_NOT_IMPORTING,
	ERR_ISCSI_IO_ERROR,
	ERR_ISCSI_FAILED_TO_FINISH_MAPPING_FILE_OPERATION,
	ERR_ISCSI_BAD_IS_USER_LOCKED,
	ERR_ISCSI_BAD_LUN_USE,
	ERR_ISCSI_BAD_SNAPSHOT_TYPE,
	ERR_ISCSI_BAD_PARENT_UUID,
	ERR_ISCSI_FAILED_TO_GET_LOOPBACK_DEV_PATH,
	ERR_ISCSI_FAILED_TO_CHECK_IS_VHOST_MAPPED,
	ERR_ISCSI_BAD_LUN_CATEGORY,
	ERR_ISCSI_BAD_LUN_FEASIBILITY_CHECK_TYPE,
	ERR_ISCSI_FAILED_TO_CHECK_LUN_FEASIBILITY,
	ERR_ISCSI_LUN_HARD_FEASIBILITY_CHECK_NOT_PASSED,
	ERR_ISCSI_LUN_SOFT_FEASIBILITY_CHECK_NOT_PASSED,
	ERR_ISCSI_BAD_IS_SOFT_FEAS_IGNORED,
	ERR_ISCSI_IMPORT_KERNEL_SUCCESS,
	ERR_ISCSI_IMPORT_CHECKSUM_ERROR,
	ERR_ISCSI_BAD_NEW_TYPE,
	ERR_ISCSI_BAD_NEW_LOCATION,
	// End of LUN error code
	ERR_ISCSI_MAX_ERROR_CODE_LUN,

	/*** Target ***/
	ERR_ISCSI_BAD_TARGET_NAME                    = ISCSI_BASE_ERROR_CODE_TARGET,
	ERR_ISCSI_BAD_TARGET_IQN,
	ERR_ISCSI_BAD_TARGET_AUTH_TYPE,
	ERR_ISCSI_BAD_TARGET_MAX_SESSIONS,
	ERR_ISCSI_BAD_TARGET_USER,
	ERR_ISCSI_BAD_TARGET_PASSWORD,
	ERR_ISCSI_BAD_TARGET_MUTUAL_USER,
	ERR_ISCSI_BAD_TARGET_MUTUAL_PASSWORD,
	ERR_ISCSI_BAD_TARGET_AUTH_INFO,
	ERR_ISCSI_BAD_TARGET_PERMISSION,
	ERR_ISCSI_BAD_TARGET_ID,
	ERR_ISCSI_BAD_TARGET_ACL,
	ERR_ISCSI_BAD_TARGET_ACL_AUTHORITY,
	ERR_ISCSI_NO_SUCH_TARGET,
	ERR_ISCSI_FAILED_TO_CREATE_TARGET,
	ERR_ISCSI_FAILED_TO_CREATE_ACL_MASKING,
	ERR_ISCSI_FAILED_TO_DELETE_ACL_MASKING,
	ERR_ISCSI_FAILED_TO_UPDATE_ACL_MASKING,
	ERR_ISCSI_FAILED_TO_ENABLE_TARGET,
	ERR_ISCSI_FAILED_TO_DISABLE_TARGET,
	ERR_ISCSI_FAILED_TO_DELETE_TARGET,
	ERR_ISCSI_FAILED_TO_LIST_TARGET,
	ERR_ISCSI_FAILED_TO_LOAD_TARGET,
	ERR_ISCSI_FAILED_TO_UNLOAD_TARGET,
	ERR_ISCSI_FAILED_TO_LOAD_TARGET_CONFIG,
	ERR_ISCSI_FAILED_TO_ADD_TARGET_CONFIG,
	ERR_ISCSI_FAILED_TO_UPDATE_TARGET_CONFIG,
	ERR_ISCSI_FAILED_TO_REMOVE_TARGET_CONFIG,
	ERR_ISCSI_FAILED_TO_LOAD_TARGET_MAPPING,
	ERR_ISCSI_FAILED_TO_UNLOAD_TARGET_MAPPING,
	ERR_ISCSI_FAILED_TO_REMOVE_TARGET_MAPPING,
	ERR_ISCSI_FAILED_TO_LOAD_MAPPING_CONFIG,
	ERR_ISCSI_FAILED_TO_GET_MAPPING_STATUS,
	ERR_ISCSI_FAILED_TO_ENABLE_ISERT,
	ERR_ISCSI_FAILED_TO_ENUMERATE_TARGET_NP,
	ERR_ISCSI_BAD_TARGET_EXTERNAL_IPS,
	ERR_ISCSI_BAD_TARGET_HAS_HEADER_CHECKSUM,
	ERR_ISCSI_BAD_TARGET_HAS_DATA_CHECKSUM,
	ERR_ISCSI_BAD_TARGET_MAX_RECV_SEG_BYTES,
	ERR_ISCSI_BAD_TARGET_MAX_SEND_SEG_BYTES,
	ERR_ISCSI_BAD_TARGET_INITIATOR_IQNS,
	// End of Target error code
	ERR_ISCSI_MAX_ERROR_CODE_TARGET,

	/*** Replication ***/
	ERR_ISCSI_NOT_A_SOURCE_TASK                  = ISCSI_BASE_ERROR_CODE_REPLICATION,
	ERR_ISCSI_NOT_A_SINK_TASK,
	ERR_ISCSI_NOT_A_RESTORABLE_TASK,
	ERR_ISCSI_NOT_ALLOWED_TO_DO_FULL_SYNC,
	ERR_ISCSI_TASK_NOT_RUNNING,
	ERR_ISCSI_TASK_NOT_PLAYABLE,
	ERR_ISCSI_TASK_NOT_STOPPED,
	ERR_ISCSI_TASK_IS_STOPPED,
	ERR_ISCSI_TASK_IS_LOCKED,
	ERR_ISCSI_TASK_IS_TRACK_PLAYED,
	ERR_ISCSI_NO_SUCH_TASK,
	ERR_ISCSI_NO_IDLE_TRACKS,
	ERR_ISCSI_NO_SUCH_TRACK,
	ERR_ISCSI_NO_ALIGNED_TRACK,
	ERR_ISCSI_REWIND_TO_LATEST_VERSION,
	ERR_ISCSI_AUTO_REWINDING,
	ERR_ISCSI_FAILOVER_DETECTED,
	ERR_ISCSI_STOP_SENDING_SNAPSHOT,
	ERR_ISCSI_BAD_REPLICATION_TASK_INFO,
	ERR_ISCSI_BAD_REPLICATION_TASK_UUID,
	ERR_ISCSI_BAD_SOURCE_LUN_UUID,
	ERR_ISCSI_BAD_DESTINATION_LUN_UUID,
	ERR_ISCSI_BAD_SOURCE_NODE_UUID,
	ERR_ISCSI_BAD_DESTINATION_NODE_UUID,
	ERR_ISCSI_BAD_IS_SOURCE,
	ERR_ISCSI_BAD_REPLICATION_TYPE,
	ERR_ISCSI_BAD_QUEUE_SIZE,
	ERR_ISCSI_BAD_ASYNC_PERIOD,
	ERR_ISCSI_BAD_TRACK_SIZE_LIMIT,
	ERR_ISCSI_BAD_REBASE_PERIOD,
	ERR_ISCSI_BAD_SOURCE_TASK_UUID,
	ERR_ISCSI_BAD_TASK_UUID,
	ERR_ISCSI_BAD_IS_TIME_UP,
	ERR_ISCSI_BAD_TASK_STATUS,
	ERR_ISCSI_BAD_PARENT_TASK_UUID,
	ERR_ISCSI_BAD_TRACK_UUID,
	ERR_ISCSI_BAD_TRACK_VERSION,
	ERR_ISCSI_BAD_SRC_TRACK_UUID,
	ERR_ISCSI_BAD_DST_TRACK_UUID,
	ERR_ISCSI_BAD_DROP_IDLE_TRACKS,
	ERR_ISCSI_BAD_DELETE_LUN,
	ERR_ISCSI_BAD_MAPPED_SIZE,
	ERR_ISCSI_BAD_TO_SOURCE,
	ERR_ISCSI_BAD_TRACK_NOTE,
	ERR_ISCSI_BAD_SOURCE_ADDRESS,
	ERR_ISCSI_BAD_DESTINATION_ADDRESS,
	ERR_ISCSI_BAD_SOURCE_PORT,
	ERR_ISCSI_BAD_DESTINATION_PORT,
	ERR_ISCSI_BAD_IS_FULL_SYNC_ALLOWED,
	ERR_ISCSI_BAD_IS_DATA_ENCRYPTED,
	ERR_ISCSI_BAD_DO_UPDATE_TRACK,
	ERR_ISCSI_BAD_DO_SEND_TRACK,
	ERR_ISCSI_BAD_SOURCE_SNAPSHOTS,
	ERR_ISCSI_BAD_BASE_SNAPSHOT_UUID,
	ERR_ISCSI_BAD_SENDING_SNAPSHOT_UUID,
	ERR_ISCSI_FAILED_TO_CREATE_REPLICATION_TASK,
	ERR_ISCSI_FAILED_TO_DELETE_REPLICATION_TASK,
	ERR_ISCSI_FAILED_TO_START_REPLICATION_TASK,
	ERR_ISCSI_FAILED_TO_LOAD_REPLICATION_TASK_CONFIG,
	ERR_ISCSI_FAILED_TO_GET_REPLICATION_TASK_UUID,
	ERR_ISCSI_FAILED_TO_UPDATE_TRACK,
	ERR_ISCSI_FAILED_TO_SEND_TRACK,
	ERR_ISCSI_FAILED_TO_SYNC_SOURCE_TASK,
	ERR_ISCSI_FAILED_TO_SYNC_DESTINATION_TASK,
	ERR_ISCSI_FAILED_TO_LIST_TASK,
	ERR_ISCSI_FAILED_TO_GET_TRACK_STATUS,
	ERR_ISCSI_FAILED_TO_LIST_TRACK,
	ERR_ISCSI_FAILED_TO_GET_TRACK_INFO,
	ERR_ISCSI_FAILED_TO_FREEZE_TASK,
	ERR_ISCSI_FAILED_TO_CONVERT_TASK,
	ERR_ISCSI_FAILED_TO_LOAD_TRACK,
	ERR_ISCSI_FAILED_TO_UNLOAD_TRACK,
	ERR_ISCSI_FAILED_TO_RESTORE_TASK,
	ERR_ISCSI_FAILED_TO_REBASE_TASK,
	ERR_ISCSI_FAILED_TO_SET_STATUS,
	ERR_ISCSI_FAILED_TO_UNSET_STATUS,
	ERR_ISCSI_FAILED_TO_GET_BASE_VERSION,
	ERR_ISCSI_FAILED_TO_GET_PROGRESS,
	ERR_ISCSI_FAILED_TO_DO_TASK_ACTION,
	ERR_ISCSI_FAILED_TO_COMPLETE_RESTORE,
	ERR_ISCSI_FAILED_TO_COMPLETE_REBASE,
	ERR_ISCSI_FAILED_TO_PAUSE_SENDING,
	ERR_ISCSI_FAILED_TO_GET_PLAYING_CANDIDATE,
	ERR_ISCSI_FAILED_TO_CLONE_TRACK,
	ERR_ISCSI_FAILED_TO_DELETE_TRACK,
	ERR_ISCSI_FAILED_TO_SET_BASE_SNAPSHOT,
	ERR_ISCSI_FAILED_TO_SEND_SNAPSHOT,
	ERR_ISCSI_FAILED_TO_COMPUTE_UNSYNC_SIZE,
	ERR_ISCSI_FAILED_TO_CREATE_REPLICA_LUN,
	// End of Replication error code
	ERR_ISCSI_MAX_ERROR_CODE_REPLICATION,

	/*** vLUN ***/
	ERR_ISCSI_BAD_VLUN_TYPE                      = ISCSI_BASE_ERROR_CODE_VLUN,
	ERR_ISCSI_BAD_VLUN_UUID,
	ERR_ISCSI_NO_VLUN_UUID,
	ERR_ISCSI_FAILED_TO_CREATE_VLUN,
	ERR_ISCSI_FAILED_TO_BIND,
	ERR_ISCSI_FAILED_TO_LOAD_VLUN_CONFIG,
	ERR_ISCSI_FAILED_TO_DELETE_VLUN,
	ERR_ISCSI_FAILED_TO_LOAD_VLUN_STATUS,
	ERR_ISCSI_FAILED_TO_LOAD_NAA,
	ERR_ISCSI_FAILED_TO_UNLOAD_NAA,
	// End of vLUN error code
	ERR_ISCSI_MAX_ERROR_CODE_VLUN,

	/*** Node ***/
	ERR_ISCSI_BAD_NODE_UUID                      = ISCSI_BASE_ERROR_CODE_NODE,
	ERR_ISCSI_BAD_NODE_HOSTNAME,
	ERR_ISCSI_BAD_NODE_PORT,
	ERR_ISCSI_BAD_NODE_PROTOCOL,
	ERR_ISCSI_BAD_NODE_ROD_KEY,
	ERR_ISCSI_BAD_NODE_ACCOUNT,
	ERR_ISCSI_BAD_NODE_PASSWORD,
	ERR_ISCSI_BAD_NODE_OTP_CODE,
	ERR_ISCSI_INVALID_NET_FAMILY,
	ERR_ISCSI_NO_SUCH_NODE,
	ERR_ISCSI_NO_NODE_UUID,
	ERR_ISCSI_NODE_UUID_EXISTS,
	ERR_ISCSI_FAILED_TO_LOAD_NODE_CONFIG,
	ERR_ISCSI_FAILED_TO_INIT_CGI,
	ERR_ISCSI_FAILED_TO_GET_AUTH_TYPE,
	ERR_ISCSI_FAILED_TO_SET_CGI_OPTION,
	ERR_ISCSI_FAILED_TO_LOGIN_WITHOUT_AUTH,
	ERR_ISCSI_FAILED_TO_LOAD_ROD_KEY,
	ERR_ISCSI_FAILED_TO_SET_ROD_KEY,
	ERR_ISCSI_FAILED_TO_GET_ROD_KEY,
	ERR_ISCSI_FAILED_TO_LIST_NODES,
	ERR_ISCSI_FAILED_TO_GET_ADDRESS_INFO,
	ERR_ISCSI_BAD_NODE_SUBVOL_ROOT_PATH,
	ERR_ISCSI_BAD_NODE_SUBVOL_PROGRESS_STATUS,
	ERR_ISCSI_SUBVOL_CONV_RUNNING,
	ERR_ISCSI_BAD_NODE_ISCSI_DIR_ROOT_PATH,
	// End of Node error code
	ERR_ISCSI_MAX_ERROR_CODE_NODE,

	ERR_ISCSI_FAILED_TO_CONNECT_TARGET           = ISCSI_BASE_ERROR_CODE_LUNBKP,
	ERR_ISCSI_FAILED_TO_DISCONNECT_TARGET,
	ERR_ISCSI_BAD_LUNBKP_TYPE,
	ERR_ISCSI_FAILED_TO_GET_NR_WRITE_THREAD,
	ERR_ISCSI_SMARTDD_FAILED,
	ERR_ISCSI_BAD_BLOCK_DEV_PATH,
	ERR_ISCSI_FAILED_TO_READLINK,
	ERR_ISCSI_BAD_LUNBKP_ESTIMATE_SIZE,
	// End of lun backup error code
	ERR_ISCSI_MAX_ERROR_CODE_LUNBKP
} ISCSI_ERROR_CODE;
/***********************************************************************************************/
/*  MUST READ: If add a new error code here, please add a corresponding error string as well.  */
/***********************************************************************************************/

static const char * const rgErrorStringBasic[ERR_ISCSI_MAX_ERROR_CODE_BASIC - ISCSI_BASE_ERROR_CODE_BASIC] =
{
	"Default error code",
	"Out of memory",
	"Out of free space",
	"Null pointer",
	"Bad parameter",
	"Bad file system type",
	"Bad file type",
	"Bad file size",
	"Bad string length",
	"No permission",
	"Timeout",
	"File not found",
	"File exists",
	"Try again",
	"Failed to fork",
	"Failed to lock file",
	"Failed to unlock file",
	"Failed to get file session",
	"Failed to set file session",
	"Failed to add file session",
	"Failed to remove file session",
	"Failed to stat path",
	"Failed to access path",
	"Failed to touch file",
	"Failed to flush or close file",
	"Failed to copy string",
	"Failed to open directory",
	"Failed to close directory",
	"Failed to cerate directory",
	"Failed to remove directory",
	"Failed to insmod kernel module",
	"Failed to rmmod kernel module",
	"Failed to set hash value",
	"Failed to get hash value",
	"Failed to set pairs",
	"Failed to get pairs",
	"Failed to link file",
	"Failed to unlink file",
	"Failed to open file",
	"Failed to read file",
	"Failed to write file",
	"Failed to seek file",
	"Failed to rename file",
	"Failed to copy file",
	"Failed to glob",
	"Failed to start service",
	"Failed to stop service",
	"Failed to get file path",
	"Failed to allocate file",
	"Failed to get time",
	"Failed to parse string",
	"Failed to get hostent",
	"Failed to get filesystem info",
	"Failed to pin volume",
	"Failed to mount",
	"Failed to get hostname",
	"Failed to get truncate mode",
	"Failed to truncate file",
	"Directory exists",
	"Failed to enumerate directory",
	"Failed to rename directory",
	"Failed to kill process",
};

static const char * const rgErrorStringWebapi[ERR_ISCSI_MAX_ERROR_CODE_WEBAPI - ISCSI_BASE_ERROR_CODE_WEBAPI] =
{
	"No such API",
	"Invalid input",
	"Bad client input",
	"Bad IP",
	"Bad response",
	"Failed to login",
	"Failed to logout",
	"Failed to create request",
	"Failed to convert to json",
	"Failed to get uuid",
	"Failed to get session ID",
	"Failed to send the request",
	"Failed to get error code",
	"Not implemented yet",
};

static const char * const rgErrorStringDSM[ERR_ISCSI_MAX_ERROR_CODE_DSM - ISCSI_BASE_ERROR_CODE_DSM] =
{
	"Failed to get volume info",
	"Failed to enumerate section",
	"Failed to enumerate config section",
	"Failed to get section",
	"Failed to add section",
	"Failed to set section",
	"Failed to remove section",
	"Failed to modify section",
	"Failed to push to list",
	"Failed to get from list",
	"Failed to parse header",
	"Failed to parse volume ID",
	"Failed to init plugin hook",
	"Failed to run plugin action",
	"Failed to get serial number",
	"Failed to send notification",
	"Failed to get space device size",
	"Failed to create Btrfs subvolume",
	"Failed to delete Btrfs subvolume",
	"Failed to get network interface",
	"Failed to get NIC PCI name",
	"Failed to get hardware vendor",
};

static const char * const rgErrorStringISCSI[ERR_ISCSI_MAX_ERROR_CODE_ISCSI - ISCSI_BASE_ERROR_CODE_ISCSI] =
{
	"Bad EP file type",
	"Bad EP file path",
	"Bad portals",
	"Bad description",
	"Bad deleted_by",
	"Need LIO support",
	"No portal",
	"No plugin notified",
	"Failed to plugin-notify",
	"Failed to plugin-start",
	"Failed to plugin-end",
	"Failed to create object file",
	"Failed to create communication",
	"Failed to fill EP file",
	"Failed to get mapped size",
	"Failed to add extent pool",
	"Failed to create EPIO journal",
	"Inconsistent EPIO journal",
	"Failed to enable extent pool",
	"Failed to disable extent pool",
	"Failed to set volume ID",
	"Failed to set map file path",
	"Failed to create progress file",
	"Failed to delete progress file",
	"Failed to set progress file",
	"Failed to get iSCSIConfig",
	"Failed to generate UUID",
	"iSCSI directory not found",
	"Bad port",
	"Failed to get space path of vspace",
	"Not accepted by filter",
	"Plugin abort depart task",
};

static const char * const rgErrorStringLUN[ERR_ISCSI_MAX_ERROR_CODE_LUN - ISCSI_BASE_ERROR_CODE_LUN] =
{
	"Bad LUN type",
	"Bad LUN location",
	"Bad LUN size",
	"Bad LUN name",
	"Bad LUN ID",
	"Bad LUN UUID",
	"Bad LUN is_same_pool",
	"Bad LUN extent_size",
	"Bad source LUN UUID",
	"Bad destination LUN UUID",
	"Bad exporting location",
	"Bad exporting LUN name",
	"Bad exported LUN UUID",
	"Bad snapshot_name",
	"Bad is_locked",
	"Bad is_app_consistent",
	"Bad is_count_only",
	"Bad additional",
	"Bad snapshot_note",
	"Bad snapshot ID",
	"Bad snapshot UUID",
	"Bad snapshot time",
	"Bad new_name",
	"Bad new_size",
	"Bad app_key",
	"Bad export_status",
	"Bad import_status",
	"Bad is_scheduled",
	"Bad is_for_trash",
	"Bad is_for_unsync_size",
	"No LUN UUID",
	"No such LUN",
	"No such snapshot",
	"No such family",
	"LUN is mapped",
	"LUN is locked",
	"LUN not loaded",
	"LUN config repaired",
	"Duplicated LUN name",
	"Cannot clone a block LUN",
	"Cannot delete locked snapshot",
	"Reach max LUN count",
	"Reach max target count",
	"Reach max snapshot count",
	"Family config repaired",
	"Snapshot config repaired",
	"Snapshot not loaded",
	"Snapshot is locked",
	"Failed to create LUN",
	"Failed to convert to sink",
	"Failed to load LUN config",
	"Failed to delete LUN",
	"Failed to clone LUN",
	"Failed to mirror LUN",
	"Failed to promote LUN",
	"Failed to get LUN ID",
	"Failed to add LUN config",
	"Failed to list LUN",
	"Failed to load family config",
	"Failed to add family config",
	"Failed to remove family config",
	"Failed to remove snapshot",
	"Failed to remove retention policy",
	"Failed to run retention policy",
	"Failed to remove LUN backup task",
	"Failed to remove schedule snapshot task",
	"Failed to get extent size",
	"Failed to get snapshot count",
	"Failed to access family config",
	"Failed to take a snapshot",
	"Failed to map target",
	"Failed to get snapshot info",
	"Failed to get new snapshot name",
	"Failed to load snapshot config",
	"Failed to clone snapshot",
	"Failed to load snapshot",
	"Failed to unload snapshot",
	"Failed to enable snapshot",
	"Failed to load LUN",
	"Failed to unload LUN",
	"Failed to get unused lid",
	"Failed to get unused sid",
	"Failed to update LUN",
	"Failed to get update LUN backup task",
	"Failed to pass space check",
	"Failed to finish export",
	"Failed to finish import",
	"Failed to get LUN status",
	"Export interrupt",
	"Import interrupt",
	"Now is exporting",
	"Now is importing",
	"Now is not exporting",
	"Now is not importing",
	"I/O error",
	"Failed to finish mapping file operation",
	"Bad is_user_locked",
	"Bad lun use",
	"Bad snapshot type",
	"Bad parent UUID",
	"Failed to get loopback device path",
	"Failed to check if LUN is mapped to vhost",
	"Bad lun category",
	"Bad lun feasibility check type",
	"Failed to check LUN feasibility",
	"LUN hard feasibility check not passed",
	"LUN soft feasibility check not passed",
	"Bad is_soft_feas_ignored",
	"Import kernel success",
	"Import checksum error",
	"Bad new type",
	"Bad new location",
};

static const char * const rgErrorStringTarget[ERR_ISCSI_MAX_ERROR_CODE_TARGET - ISCSI_BASE_ERROR_CODE_TARGET] =
{
	"Bad target name",
	"Bad target iqn",
	"Bad target auth_type",
	"Bad target max_sessions",
	"Bad target user",
	"Bad target password",
	"Bad target mutual_user",
	"Bad target mutual_password",
	"Bad target auth info",
	"Bad target permission",
	"Bad target ID",
	"Bad target acl",
	"Bad target acl authority",
	"No such target",
	"Failed to create target",
	"Failed to create ACL masking",
	"Failed to delete ACL masking",
	"Failed to update ACL masking",
	"Failed to enable target",
	"Failed to disable target",
	"Failed to delete target",
	"Failed to list target",
	"Failed to load target",
	"Failed to unload target",
	"Failed to load target config",
	"Failed to add target config",
	"Failed to update target config",
	"Failed to remove target config",
	"Failed to load target mapping",
	"Failed to unload target mapping",
	"Failed to remove target mapping",
	"Failed to load mapping config",
	"Failed to get mapping status",
	"Failed to enable isert",
	"Failed to enumerate target network portals",
	"Bad target external ips",
	"Bad target has_header_checksum",
	"Bad target has_data_checksum",
	"Bad target max_recv_seg_bytes",
	"Bad target max_send_seg_bytes",
	"Bad target initiator_iqns",
};

static const char * const rgErrorStringReplication[ERR_ISCSI_MAX_ERROR_CODE_REPLICATION - ISCSI_BASE_ERROR_CODE_REPLICATION] =
{
	"Not a source task",
	"Not a destination task",
	"Not a restorable task",
	"Not allowed to do full sync",
	"Task is not running",
	"Task is not playable",
	"Task is not stopped",
	"Task is stopped",
	"Task is locked",
	"Task is track played",
	"No such task",
	"No idle tracks",
	"No such track",
	"No aligned track",
	"Rewind to latest version",
	"Auto rewinding",
	"Failover detected",
	"Stop sending snapshot",
	"Bad replication task info",
	"Bad replication task UUID",
	"Bad source LUN UUID",
	"Bad destination LUN UUID",
	"Bad source Node UUID",
	"Bad destination Node UUID",
	"Bad is_source",
	"Bad replication type",
	"Bad queue size",
	"Bad async period",
	"Bad track size limit",
	"Bad rebase period",
	"Bad source task UUID",
	"Bad task UUID",
	"Bad is_time_up",
	"Bad task status",
	"Bad parent task UUID",
	"Bad track UUID",
	"Bad track version",
	"Bad source track UUID",
	"Bad destination track UUID",
	"Bad drop_idle_tracks",
	"Bad delete_lun",
	"Bad mapped_size",
	"Bad to_source",
	"Bad track_note",
	"Bad source address",
	"Bad destination address",
	"Bad source port",
	"Bad destination port",
	"Bad is_full_sync_allowed",
	"Bad is_data_encrypted",
	"Bad do_update_track",
	"Bad do_send_track",
	"Bad source_snapshots",
	"Bad base_snapshot_uuid",
	"Bad sending_snapshot_uuid",
	"Failed to create replication task",
	"Failed to delete replication task",
	"Failed to start replication task",
	"Failed to load replication task config",
	"Failed to get replication task UUID",
	"Failed to update track",
	"Failed to send track",
	"Failed to sync source task",
	"Failed to sync destination task",
	"Failed to list task",
	"Failed to get track status",
	"Failed to list track",
	"Failed to get track info",
	"Failed to freeze task",
	"Failed to convert task",
	"Failed to load track",
	"Failed to unload track",
	"Failed to restore task",
	"Failed to rebase task",
	"Failed to set status",
	"Failed to unset status",
	"Failed to get base version",
	"Failed to get progress",
	"Failed to do task action",
	"Failed to complete restore",
	"Failed to complete rebase",
	"Failed to pause sending track",
	"Failed to get playing candidate",
	"Failed to clone track",
	"Failed to delete track",
	"Failed to set base snapshot",
	"Failed to send snapshot",
	"Failed to compute unsync size",
	"Failed to create replica LUN",
};

static const char * const rgErrorStringVLUN[ERR_ISCSI_MAX_ERROR_CODE_VLUN - ISCSI_BASE_ERROR_CODE_VLUN] =
{
	"Bad vLUN type",
	"Bad vLUN UUID",
	"No vLUN UUID",
	"Failed to create vLUN",
	"Failed to bind",
	"Failed to load vLUN config",
	"Failed to delete vLUN",
	"Failed to load vLUN status",
	"Failed to load NAA",
	"Failed to unload NAA",
};

static const char * const rgErrorStringNode[ERR_ISCSI_MAX_ERROR_CODE_NODE - ISCSI_BASE_ERROR_CODE_NODE] =
{
	"Bad node UUID",
	"Bad node hostname",
	"Bad node port",
	"Bad node protocol",
	"Bad node ROD key",
	"Bad node account",
	"Bad node password",
	"Bad node OTP code",
	"Invaild net family",
	"No such node",
	"No node UUID",
	"Node UUID exists",
	"Failed to load node config",
	"Failed to init CGI",
	"Failed to get auth type",
	"Failed to set CGI option",
	"Failed to login without auth",
	"Failed to load ROD key",
	"Failed to set ROD key",
	"Failed to get ROD key",
	"Failed to list nodes",
	"Failed to get address info",
	"Bad subvolume root path",
	"Bad subvolume progress status",
	"Subvolume convert is running",
	"Bad iSCSI directory rootpath",
};

static const char *const rgErrorStringLunBkp[ERR_ISCSI_MAX_ERROR_CODE_LUNBKP - ISCSI_BASE_ERROR_CODE_LUNBKP] =
{
	"Failed to connect to target",
	"Failed to disconnect from target",
	"Bad lunbkp type",
	"Failed to get nr_write_thread from synoinfo",
	"Smartdd failed",
	"Bad block device path",
	"Failed to readlink",
	"Bad lunbkp estimate size",
};

static inline const char * SYNOiSCSIStrError(int errorCode)
{
	const char * ret = NULL;

	if (ISCSI_BASE_ERROR_CODE_BASIC <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_BASIC > errorCode) {
		ret = rgErrorStringBasic [errorCode - ISCSI_BASE_ERROR_CODE_BASIC];
	} else if (ISCSI_BASE_ERROR_CODE_WEBAPI <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_WEBAPI > errorCode) {
		ret = rgErrorStringWebapi[errorCode - ISCSI_BASE_ERROR_CODE_WEBAPI];
	} else if (ISCSI_BASE_ERROR_CODE_DSM <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_DSM > errorCode) {
		ret = rgErrorStringDSM[errorCode - ISCSI_BASE_ERROR_CODE_DSM];
	} else if (ISCSI_BASE_ERROR_CODE_ISCSI <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_ISCSI > errorCode) {
		ret = rgErrorStringISCSI[errorCode - ISCSI_BASE_ERROR_CODE_ISCSI];
	} else if (ISCSI_BASE_ERROR_CODE_LUN <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_LUN > errorCode) {
		ret = rgErrorStringLUN[errorCode - ISCSI_BASE_ERROR_CODE_LUN];
	} else if (ISCSI_BASE_ERROR_CODE_TARGET <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_TARGET > errorCode) {
		ret = rgErrorStringTarget[errorCode - ISCSI_BASE_ERROR_CODE_TARGET];
	} else if (ISCSI_BASE_ERROR_CODE_REPLICATION <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_REPLICATION > errorCode) {
		ret = rgErrorStringReplication[errorCode - ISCSI_BASE_ERROR_CODE_REPLICATION];
	} else if (ISCSI_BASE_ERROR_CODE_VLUN <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_VLUN > errorCode) {
		ret = rgErrorStringVLUN[errorCode - ISCSI_BASE_ERROR_CODE_VLUN];
	} else if (ISCSI_BASE_ERROR_CODE_NODE <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_NODE > errorCode) {
		ret = rgErrorStringNode[errorCode - ISCSI_BASE_ERROR_CODE_NODE];
	} else if (ISCSI_BASE_ERROR_CODE_LUNBKP <= errorCode && ERR_ISCSI_MAX_ERROR_CODE_LUNBKP > errorCode) {
		ret = rgErrorStringLunBkp[errorCode - ISCSI_BASE_ERROR_CODE_LUNBKP];
	} else if (0 > errorCode && -256 < errorCode) {
		ret = strerror(errorCode * -1);
	} else {
		ret = strerror(errorCode);
	}

	return ret ? ret : "Undefined error string";
}

static int SYNOiSCSIExportImportKernelErrToiSCSIErr(int errorCode, int isExport)
{
	switch (errorCode) {
	case 0:
		if (isExport) {
			return ERR_ISCSI_SUCCESS;
		} else {
			return ERR_ISCSI_IMPORT_KERNEL_SUCCESS;
		}
	case 1:
	case -EBUSY:
		if (isExport) {
			return ERR_ISCSI_NOW_IS_EXPORTING;
		} else {
			return ERR_ISCSI_NOW_IS_IMPORTING;
		}
	case -ENOENT:
		return ERR_ISCSI_FILE_NOT_FOUND;
	case -EINTR:
		if (isExport) {
			return ERR_ISCSI_EXPORT_INTERRUPT;
		} else {
			return ERR_ISCSI_IMPORT_INTERRUPT;
		}
	case -EIO:
		return ERR_ISCSI_IO_ERROR;
	case -EAGAIN:
		return ERR_ISCSI_TRY_AGAIN;
	case -ENOMEM:
		return ERR_ISCSI_OUT_OF_MEMORY;
	case -ENOSPC:
		return ERR_ISCSI_OUT_OF_FREE_SPACE;
	case -ESPIPE:
		return ERR_ISCSI_FAILED_TO_FINISH_MAPPING_FILE_OPERATION;
	case -EINVAL:
		return ERR_ISCSI_BAD_PARAMETER;
	default:
		if (isExport) {
			return ERR_ISCSI_FAILED_TO_FINISH_EXPORT;
		} else {
			return ERR_ISCSI_FAILED_TO_FINISH_IMPORT;
		}
	}
}

#define TRACELOG(errorcode, format, ...) syslog(LOG_ERR, "iSCSI:%s:%d:%s " format " failed, err=%s", \
	(strrchr(__FILE__, '/') ? strrchr(__FILE__, '/') + 1 : __FILE__), __LINE__, __func__, ## __VA_ARGS__, SYNOiSCSIStrError(errorcode))

#define SetiRetAndGoToEND(errorCode) do { iRet = (errorCode); goto END; } while (0)

__END_DECLS

#endif // _SYNOISCSIEP_ERROR_H_
