#ifndef MY_ABC_HERE
#define MY_ABC_HERE
#endif
/* A config file included by config.h.
 * reposonsible for all Synology related definitions
 */
#ifndef _SYNO_AT_CONFIG
#define _SYNO_AT_CONFIG

// include syno platform define
#include <linux/syno.h>

/* Let pid path = /var/run/X.pid (afpd, atalkd, papd, cnid_metad) */
/* Fix Coredump */
/* B#24454: Sync stale dircache as rename app */
/* B#26372, 25530: check corrupted dsi packet. */

/* Move the .AppleDB to somewhere normal users could not reach */
/* Fix Bug 14466: might core dump while doing cnid operation
 * Replace the abort() with error and return.
 */ 
/** Fix Bug#26710: use 127.0.0.1 for cnid_metad host 
 * - Use 127.0.0.1 to avoid DNS look up failure in some platform
 * - report error when getaddrinfo failed
 */

/* Fix Bug 20997: shift the cnid start value (CNID_START) to 3500,000 to avoid rename problem with "#[digits]"
 * This solution would solve naming problems of "xxxx#[1-356799]"
 */

/* Record file:line in syslog mode. */

/* Use Synology Authentication to check user */
/* Add username utf8 conversion to compatible with old client (OS 9, afp < 3.0) */
/* Add speed up for DHX2 auth on platform 6281, 6180 */

/* Let afp conversion function supports addtional code page */
/** Fix Bug #777, #25810 - Allow MAC to use '/' in filename
 * => Convert / from 0x2f to 0xf022 */

/* Give admin the root privilage, excepts creating file/dir.(Bug#1024)
 * Take cares of the owner/group of new uploaded file/dir.
 * Also fix bug 19089, which makes members in the admin group have root privilage
 */
/** Fix Bug 27010: Use username to check auth (instead of geteuid) while timeout
 */
//
/* Load synology shared folder as default volumes */
/* Don't create special_folders such as .AppleDesktop */
/* Fix Volume quota problem */
#include <synocore/synoglobal.h>
#undef MAXPATHLEN
#define MAXPATHLEN MAX_PATH_LEN
#undef NO_QUOTA_SUPPORT

/* Let afp reload user/volume related info as SIGHUP */
#define SZ_AFP_NGUEST_MOD	"uamsNguest.so"
#define SZ_AFP_GUEST_MOD	"uams_guest.so"

/* Let afp support Synology EA */
/* Rename sys_ftruncate to avoid conflict with smbd's sys_ftruncate */
/**
 * Fix Bug #13581, #38215:
 * Since usbshare doesn't have entry to store the data into ._file.
 * Activate the entry like the normal share.
 */

/* Fix Bug 20220: Let cnid_metad support maxshares limit of synoinfo.conf.
 * And check if the protocol limitation(255 volume) is reached.
 */

/* Set case sensitive bit for vol param */

/* Use Syno ACL API to do chmod action */

/** Fix Bug 24665: Revise EC_FAIL macro which cause search failed */

/* Let AFP detect / sync the some attribute of samba 
 * Lock <-> ReadOnly
 * Invisiable <-> Hide
 */

/** Fix Bug 26479: In CIFS, don't open data/resource fork to lock file.
 * Let cifs to deal with lock problem
 */
/**
 * Fix Bug 47863: Don't mkdir @eaDir across different dev.
 */

/**
 * Fix bug #33871, #34063: 
 * avoid unnecessary db check since it would break hibernation
 */

/*
 * Apply framework for improve uploading performance.
 * MY_ABC_HERE should turn on in MY_ABC_HERE/MY_DEF_HERE
 */
#if defined(MY_DEF_HERE)
#elif !defined(MY_DEF_HERE)
#endif
/*
 * Netatalk-3.x has error in recvfile without splice.
 */

/**
 * Fix Bug #36097: Support syno recycle bin
 */

/**
 * Fix Bug #36610: 
 * Since some application would create data files with slnk type.
 * So, don't create symbolic link if the input file isn't a link file
 */
//
//#define SYNO_PERFORMANCE_NO_VETO_FILE

/**
 * Fix Bug #56147, Reduce sync in BDB
 * Add DB_TXN_NOSYNC, DB_TXN_WRITE_NOSYNC when dbd open.
 */

/**
 * Fix Bug #41038:
 * Since netatalk always use the modify time as the create time when the file doesn't
 * any have apple double file.
*/
/**
 * Fix Bug #41684
 * The folder will be gray when wrong create time in OSX 10.8. The create time sets
 * "Tue Jan 24 16:00:00 1984" (44377920) when using SMB convey the folder has EA.
*/

#ifdef MY_ABC_HERE
#define SMB_WRONG_CREATE_TIME 443779200
#endif
/**
 * Fix Bug #38214:
 * Apple will return the character, '\r'. But FAT/NTFS cannot use this character.
 * So the icon file, "Icon\r" cannot store into FAT/NTFS.
 */
/**
 * Fix Bug #44376:
 * Performance issue on FAT
 * The close function spends about 0.01 seconds when opening with O_RDWR flags.
 * open fucntion avoids with the O_RDWR flags if unnecessary.
 */
/**
 * Fix Bug #43696:
 * Avoiding fsync for performance
 */
/**
 * Fix Bug #38214:
 * The apple double file (._file) generated by MAC includes attributes,
 * which causes the bad resource fork because of exceeding the buf, 1024.
*/
/*
 * Fix Bug #44354:
 * SynoResource whose has EA from usbshare should be modified
 */
/*
 * For Bug #53933:
 * Reduce close_write event on open for set modified time
 */
/*
 * Fix Bug #51831
 * If name cannot convert, name table will insert wrong key.
 */

/*
 * Fix Bug #55657
 * DSI should bind IPv6 interface first.
 */

/*
 * Fix Bug #44779
 * FAT/NTFS support EA
 */

#if defined(MY_DEF_HERE)
#if defined(MY_DEF_HERE)
	#define SZ_SYNO_TASKSET_CORE "1"
#else
	#define SZ_SYNO_TASKSET_CORE "2"
#endif
#endif

/*
 * For avoiding write unused apple double entry into apple double file.
 */

#ifdef MY_ABC_HERE
#define SYNO_SENDFILE_SIZE 32768
#endif
/** Fix Bug <DSM> #71723: btrfs user and share quota for afp
 * - Use ioctl read btrfs share user quota and share quota
 */

/**
 * For DSM #27477: Send quota refresh request to synoconfd after login success.
 */

#define SYNO_SPOTLIGHT

/**
 * <DSM> #97318 - support btrfs clone (reflink copy)
 */

/*****************************************************/
/* For Profiling usage                               */
/*****************************************************/
#if 0
#define SYNO_PROFILING
#endif

#endif /* _SYNO_AT_CONFIG */
