// Copyright (c) 2000-2013 Synology Inc. All rights reserved.
#ifndef __SYNO_MYDS_ERR_H__
#define __SYNO_MYDS_ERR_H__

__BEGIN_DECLS;

/*
 * Packages depend on this enum, all new error code should be "append" to last
 */
typedef enum MYDS_ERRCODE {
	MYDS_SUCCESS = 0,
	MYDS_ERR_WRONG_PARAMS,
	MYDS_ERR_WRONG_JSON,
	MYDS_ERR_NO_MYDS_ACCOUNT,
	MYDS_ERR_SEND,
	MYDS_ERR_RESPONSE,
	MYDS_ERR_SYS,
	MYDS_ERR_NO_PAYMENT_CFG,
	MYDS_ERR_SERIAL,
	MYDS_ERR_WRONG_FILE_FORMAT,
	MYDS_ERR_PUBLIC_KEY_GET,
	MYDS_ERR_PUBLIC_KEY_VERIFY,
	MYDS_ERR_SYNOPAYMENT,
	MYDS_ERR_SYNOPAYMENT_SIGN_GET,
	MYDS_ERR_BAD_AUTH,
	MYDS_ERR_BAD_NERWORK,
	MYDS_ERR_ACCOUNT_INUSED,
	MYDS_ERR_EXCEED_REGISTER_MAX,
	MYDS_ERR_UNVERIFIED,
	MYDS_ERR_CONF_WRITE,
	MYDS_ERR_MAC_ADDRESS,
	MYDS_ERR_API_KEY,
	MYDS_ERR_TOKEN,
	MYDS_ERR_SYNOPAYMENT_CONF,
	MYDS_ERR_UNKNOWN,
	MYDS_ERR_ACCOUNT_NOT_FOUND,
	MYDS_ERR_API_KEY_NOT_FOUND,
	MYDS_ERR_API_KEY_EXPIRED
} MYDS_ERRCODE;

struct MyDSErrorCodeMap
{
	const char* szErrorMsg;
	MYDS_ERRCODE code;
};

__END_DECLS;
#endif // __SYNO_MYDS_ERR_H__
